name: CMake on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
      shell: cmd

    - name: Install SFML
      run: .\vcpkg\vcpkg install sfml
      shell: cmd

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
      shell: cmd

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
      shell: cmd

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}}
      shell: cmd

    - name: Output Build Logs
      if: failure()
      run: |
        type build\CMakeFiles\CMakeError.log
        type build\CMakeFiles\CMakeOutput.log
      shell: cmd
